#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


#set the two first no of the sequence and the answer
solution,a, b = 0, 1, 2

#continue if b is less than 4000000
while b < 4000000:
    #check if b is even
        if b % 2 == 0:
            #if found add b to answer
            solution += b

        #fibonacci property
        a,b = b, a+b

print(solution)




